name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build React App
      run: |
        echo "REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}" > .env
        CI=false npm run build
      
    - name: Debug Dist Directory
      run: |
        ls -lah dist/ || echo "⚠️ dist directory does not exist!"

    - name: Ensure Target Directory Exists
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          sudo mkdir -p /var/www/react-app
          sudo chown -R $USER:$USER /var/www/react-app
          sudo chmod -R 755 /var/www/react-app

    - name: Deploy to AWS EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        source: "dist/*"
        target: "/var/www/react-app"
        strip_components: 1
        debug: true

        # rm: true

    - name: Restart Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          sudo systemctl restart nginx